import { useState } from "react";
import type { Appearance, AppearancePreset, ConversationBubbleVariant, InterfaceFont, ThemeMode } from "../types";
import { DEFAULT_APPEARANCE } from "../constants";

type ColorKey = "accent" | "icon" | "canvas" | "surface" | "stage" | "text" | "avatar";
type PresetColorKey = ColorKey | "chatSurface" | "chatUser" | "chatAssistant" | "chatText" | "chatAccent";
const COLORS: Array<[ColorKey, string]> = [["accent", "Accent"], ["icon", "Icons"], ["canvas", "Canvas"], ["surface", "Panels"], ["stage", "Command space"], ["text", "Text"], ["avatar", "Avatar glow"]];
const FONTS: Array<[InterfaceFont, string]> = [["Ubuntu", "Friendly clarity"], ["Roboto", "Clean readability"], ["Manrope", "Quiet utility"], ["Newsreader", "Editorial warmth"], ["Space Grotesk", "Technical clarity"], ["DM Mono", "Machine precision"]];
const BUBBLE_VARIANTS: Array<[ConversationBubbleVariant, string]> = [["default", "Primary"], ["secondary", "Secondary"], ["muted", "Muted"], ["tinted", "Tinted"], ["outline", "Outline"], ["ghost", "Ghost"]];
const CHAT_COLORS: Array<[keyof Appearance, string]> = [["chatSurface", "Chat surface"], ["chatUser", "User bubble"], ["chatAssistant", "Assistant bubble"], ["chatText", "Chat text"], ["chatAccent", "Chat accent"]];

function Switch({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) {
  return <button type="button" className={`switch ${checked ? "on" : ""}`} role="switch" aria-checked={checked} aria-label={label} onClick={onChange}><span /></button>;
}

/** Modal settings surface. It owns no state; the page remains the single source of truth. */
export function AppearanceDialog({ mode, setMode, cursorGaze, setCursorGaze, appearance, setAppearance, presets, savePreset, deletePreset, onReset, onClose }: { mode: ThemeMode; setMode: (value: ThemeMode) => void; cursorGaze: boolean; setCursorGaze: (value: boolean) => void; appearance: Appearance; setAppearance: (value: Appearance) => void; presets: Record<string, AppearancePreset>; savePreset: (name: string, preset: AppearancePreset) => void; deletePreset: (name: string) => void; onReset: () => void; onClose: () => void }) {
  const [presetName, setPresetName] = useState("");
  const update = <Key extends keyof Appearance>(key: Key, value: Appearance[Key]) => setAppearance({ ...appearance, [key]: value });
  const presetKeys: PresetColorKey[] = ["accent", "icon", "canvas", "surface", "stage", "text", "avatar", "chatSurface", "chatUser", "chatAssistant", "chatText", "chatAccent"];
  const currentPreset = Object.fromEntries(presetKeys.map((key) => [key, appearance[key]])) as AppearancePreset;
  const applyPreset = (preset: AppearancePreset) => setAppearance({ ...appearance, ...preset });
  const saveCurrentPreset = () => { const name = presetName.trim(); if (!name) return; savePreset(name, currentPreset); setPresetName(""); };
  return <div className="settings-scrim" role="presentation" onMouseDown={onClose}><section className="appearance-dialog" role="dialog" aria-modal="true" aria-labelledby="appearance-title" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="eyebrow">Lumine preferences</p><h2 id="appearance-title">Appearance</h2></div><button className="dialog-close" onClick={onClose} aria-label="Close appearance settings">×</button></header><div className="appearance-body">
    <section className="setting-group"><div className="setting-title"><div><strong>Color mode</strong><p>Change Lumine’s ambient ground.</p></div><div className="segmented"><button className={mode === "light" ? "active" : ""} onClick={() => setMode("light")}>Light</button><button className={mode === "dark" ? "active" : ""} onClick={() => setMode("dark")}>Dark</button></div></div></section>
    <section className="setting-group"><div className="setting-title"><div><strong>Cursor-aware gaze</strong><p>Let Lumine’s eyes follow your cursor.</p></div><Switch checked={cursorGaze} onChange={() => setCursorGaze(!cursorGaze)} label="Toggle cursor-aware gaze" /></div></section>
    <section className="setting-group"><div className="setting-title"><div><strong>Avatar color</strong><p>Show the warm color around Lumine’s face.</p></div><Switch checked={appearance.showAvatarColor} onChange={() => update("showAvatarColor", !appearance.showAvatarColor)} label="Toggle avatar color" /></div></section>
    <section className="setting-group"><div className="setting-title"><div><strong>Interface type</strong><p>Choose the voice of the command space.</p></div></div><div className="font-choices">{FONTS.map(([font, description]) => <button key={font} className={`${font === "Newsreader" ? "serif" : ""} ${appearance.font === font ? "selected" : ""}`} onClick={() => update("font", font)}><b>{font}</b><span>{description}</span></button>)}</div></section>
    <section className="setting-group"><div className="setting-title"><div><strong>Conversation style</strong><p>Give the activity layer its own voice.</p></div></div><div className="font-choices">{FONTS.map(([font, description]) => <button key={`chat-${font}`} className={`${font === "Newsreader" ? "serif" : ""} ${appearance.chatFont === font ? "selected" : ""}`} onClick={() => update("chatFont", font)}><b>{font}</b><span>{description}</span></button>)}</div><div className="bubble-variant-choices">{BUBBLE_VARIANTS.map(([variant, label]) => <button key={variant} className={appearance.chatBubbleVariant === variant ? "selected" : ""} onClick={() => update("chatBubbleVariant", variant)}>{label}</button>)}</div></section>
    <section className="setting-group colors"><div className="setting-title"><div><strong>Custom palette</strong><p>Use a hex value for each visual layer.</p></div><button className="reset-link" onClick={() => setAppearance({ ...DEFAULT_APPEARANCE })}>Reset</button></div><div className="preset-save"><input value={presetName} placeholder="Name this palette" aria-label="Preset name" onChange={(event) => setPresetName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") saveCurrentPreset(); }} /><button onClick={saveCurrentPreset} disabled={!presetName.trim()}>Save preset</button></div>{Object.keys(presets).length > 0 && <div className="preset-list">{Object.entries(presets).map(([name, preset]) => <div className="preset-row" key={name}><button className="preset-choice" onClick={() => applyPreset(preset)}><span className="preset-swatch" style={{ background: preset.accent }} />{name}</button><button className="preset-delete" onClick={() => deletePreset(name)} aria-label={`Delete ${name} preset`}>×</button></div>)}</div>}<div className="color-grid">{COLORS.map(([key, label]) => <label key={key}><span>{label}</span><div><input type="color" value={appearance[key]} onChange={(event) => update(key, event.target.value)} /><input type="text" aria-label={`${label} hex color`} value={appearance[key]} maxLength={7} onChange={(event) => { if (/^#[0-9A-Fa-f]{0,6}$/.test(event.target.value)) update(key, event.target.value); }} /></div></label>)}</div><p className="setting-subheading">Conversation palette</p><div className="color-grid">{CHAT_COLORS.map(([key, label]) => <label key={String(key)}><span>{label}</span><div><input type="color" value={String(appearance[key])} onChange={(event) => update(key, event.target.value)} /><input type="text" aria-label={`${label} hex color`} value={String(appearance[key])} maxLength={7} onChange={(event) => { if (/^#[0-9A-Fa-f]{0,6}$/.test(event.target.value)) update(key, event.target.value); }} /></div></label>)}</div></section>
  </div><footer><button className="reset-all-button" onClick={onReset}>Reset all preferences</button><button onClick={onClose}>Done</button></footer></section></div>;
}
