import { invoke } from "@tauri-apps/api/core";
import type { AgentStatus } from "../../lib/agentRuntime";
import type { ConfigDocument, Diagnostic, ProviderCatalog } from "./aiConfigTypes";

/**
 * Every Tauri call the AI Control Center makes.
 *
 * The settings surface never talks to Python, LiveKit, or a provider directly.
 * Two boundaries matter:
 *
 * - **Credentials are write-only.** `setCredential` takes a secret and returns
 *   redacted status; `getCredentialStatus` returns presence and a last-four tail.
 *   There is deliberately no function here that reads a stored secret back.
 * - **Validation is server-side.** The worker owns the capability rules, so the UI
 *   renders the diagnostics it returns rather than deciding validity itself.
 */

export class DesktopUnavailableError extends Error {
  constructor() {
    super("This screen needs the Lumine desktop app. Run `npm run tauri dev`.");
    this.name = "DesktopUnavailableError";
  }
}

/**
 * The catalog shape this screen was written against. See `agent/providers.py`.
 *
 * v9 added a probe's `authKind`/`tokenPath`, which is how LiveKit became
 * testable: its credential is a URL, an API key and an API secret used together
 * to mint a token, so a probe that puts one value in one header could not check
 * it.
 *
 * v10 added a per-option `advanced` flag, so a stage leads with the settings a
 * person chooses and puts token caps and sampling knobs behind a disclosure. It
 * is declared in the catalog because only the catalog knows whether a
 * `temperature` is ordinary on one model and meaningless on another.
 *
 * v11 added each model's `inputModalities`, so Diagnostics can report what a
 * model can be given and the camera control can decline to offer itself to a
 * stack whose frames would arrive nowhere.
 *
 * v12 added a per-option `default` and `hidden`, and the local-model provider
 * that needs them. Ollama's OpenAI-compatible server has no authentication, but
 * the OpenAI client refuses to construct without a key, so Lumine sends the
 * literal string `"ollama"`. That argument has to reach the plugin while staying
 * out of the screen: a required value the user cannot usefully change is not a
 * setting, and drawing it would present a non-problem as a setup step.
 *
 * Bump in step with `CATALOG_VERSION` in `agent/providers.py`; a test asserts the
 * two agree.
 */
const CATALOG_VERSION = 12;

export class CatalogTooNewError extends Error {
  constructor(received: number) {
    super(
      `The agent ships a provider catalog this build does not understand (v${received}, expected v${CATALOG_VERSION}). Update the app.`,
    );
    this.name = "CatalogTooNewError";
  }
}

/**
 * Refuse a catalog this screen was not written for.
 *
 * The catalog is the only description of what providers, models, and voices
 * exist. Reading a field that is not there would throw somewhere deep in a
 * render, which is a confusing way to learn the agent and the app disagree.
 */
function assertCatalogVersion(catalog: ProviderCatalog): ProviderCatalog {
  if (typeof catalog?.version !== "number") {
    throw new CatalogTooNewError(Number.NaN);
  }
  if (catalog.version > CATALOG_VERSION) {
    throw new CatalogTooNewError(catalog.version);
  }
  return catalog;
}

function isTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

/** Run a Tauri command, turning "not running inside the app" into a clear error. */
async function call<T>(command: string, args?: Record<string, unknown>): Promise<T> {
  if (!isTauri()) throw new DesktopUnavailableError();
  return invoke<T>(command, args);
}

export async function getProviderCatalog(): Promise<ProviderCatalog> {
  return assertCatalogVersion(await call<ProviderCatalog>("get_provider_catalog"));
}

/**
 * One thing Lumine can do, as a person would describe it.
 *
 * Generated by `agent/tool_catalog.py` from the same registry the worker hands to
 * the model, so a tool cannot appear here without being callable. The docstring
 * on each tool is the model's schema and is deliberately not what this shows.
 */
export type CatalogTool = {
  /** The exact id the model is given, so a report can be matched to a call. */
  id: string;
  label: string;
  summary: string;
  /**
   * The id of one `ToolCategory`.
   *
   * Not a free word. The page builds its tab strip from the published category
   * list, so a value the worker has not declared would put a card behind a tab
   * that does not exist. `agent/tool_catalog.py --check` fails on that.
   */
  category: string;
  /**
   * `"answers"` only tells Lumine something. `"opens"` acts on this machine.
   *
   * The distinction is stated rather than left to the name, because it is the
   * thing a person is deciding about when they leave a tool switched on.
   */
  effect: "answers" | "opens";
  /** Whether reaching it involves the internet. */
  network: boolean;
  parameters: {
    name: string;
    kind: string;
    required: boolean;
    help: string;
  }[];
  /** False when an environment toggle has switched it off for this run. */
  enabled: boolean;
  /** Which toggle did it. Empty when enabled. */
  disabledReason: string;
};

/**
 * One group on the Tools page tab strip.
 *
 * Declared in `agent/tools/tools_registry.py` and published, order included, so
 * the strip is not alphabetical accident. The `description` is what the strip's
 * own `Hint` says: a tab that is only a word makes the reader guess what belongs
 * in it, and a card has nowhere to go if the group is misread.
 */
export type ToolCategory = {
  id: string;
  label: string;
  description: string;
};

export type ToolCatalog = {
  version: number;
  categories: ToolCategory[];
  tools: CatalogTool[];
};

/** Every tool, plus the groups they fall into. */
export type ToolCatalogResult = {
  categories: ToolCategory[];
  tools: CatalogTool[];
};

/**
 * What Lumine can currently do.
 *
 * A command failure resolves to empty lists rather than throwing: the Tools page
 * is a read-only view, and a Python helper that will not start should leave it
 * saying it does not know yet, not replace the workspace with an error. The
 * desktop layer caches the answer for the life of the process, so this is one
 * cold Python start and then an immediate read.
 */
export async function getToolCatalog(): Promise<ToolCatalogResult> {
  try {
    const catalog = await call<ToolCatalog>("get_tool_catalog");
    return {
      categories: Array.isArray(catalog.categories) ? catalog.categories : [],
      tools: Array.isArray(catalog.tools) ? catalog.tools : [],
    };
  } catch {
    return { categories: [], tools: [] };
  }
}

/**
 * One model a local server is serving.
 *
 * `size` is bytes and is present only when the server bothered to say. It is not
 * decoration: `llama3.2:3b` and a 70B model are the same number of characters to
 * somebody who has to guess what will fit in their memory, and the size is the
 * only thing in this app that can tell them.
 */
export type LocalModel = {
  id: string;
  size?: number;
};

export type LocalModelDiscovery = {
  /** Whether the server was reached. Says nothing about whether it has models. */
  ok: boolean;
  /** The address that was asked, so a person can check it against their server. */
  baseUrl: string;
  /** Which route answered, or empty when none did. */
  route: string;
  latencyMs: number;
  models: LocalModel[];
  /** A machine status, when there is one worth reporting. */
  error: string;
  /** The same thing in words a person can act on. */
  detail: string;
};

/**
 * Ask a local model server what it has.
 *
 * Resolves rather than rejects on a failed lookup, because failing *is* an answer
 * here: a server that is not running produces a sentence saying so, which is
 * exactly what the chooser needs. Only a desktop layer that is not there at all
 * rejects.
 */
export async function discoverLocalModels(baseUrl?: string): Promise<LocalModelDiscovery> {
  const trimmed = (baseUrl ?? "").trim();
  return call<LocalModelDiscovery>("discover_local_models", trimmed ? { baseUrl: trimmed } : {});
}

export type EffectiveConfig = {
  /** "ui" when a saved document governs; "env" when agent/.env still does. */
  source: "ui" | "env";
  document: ConfigDocument;
  diagnostics: Diagnostic[];
};

/** The effective configuration, with its provenance. */
export function getConfig(): Promise<EffectiveConfig> {
  return call<EffectiveConfig>("get_config");
}

export function saveConfig(document: ConfigDocument): Promise<void> {
  return call<void>("save_config", { document });
}

export type ValidationResult = {
  ok: boolean;
  errorCount: number;
  warningCount: number;
  diagnostics: Diagnostic[];
};

export function validateConfig(document: ConfigDocument): Promise<ValidationResult> {
  return call<ValidationResult>("validate_config", { document: JSON.stringify(document) });
}

export type CredentialStatus = {
  present: boolean;
  last4: string | null;
  updatedAt: string | null;
};

/**
 * Which of a provider's values is being addressed.
 *
 * Most providers have one credential and pass nothing: the bare provider id is
 * the keyring account name, which is what every key stored before slots existed
 * uses. LiveKit is the exception -- it needs a server URL, an API key and an API
 * secret, and they are not interchangeable. The slot is the environment variable
 * the value belongs in, so each of the three is stored and read separately.
 *
 * This is a variable *name*. No value ever crosses back out of Rust; a status is
 * presence plus at most four trailing characters.
 */
export function setCredential(
  provider: string,
  secret: string,
  slot?: string,
): Promise<CredentialStatus> {
  return call<CredentialStatus>("set_credential", { provider, secret, slot: slot ?? null });
}

export function deleteCredential(provider: string, slot?: string): Promise<void> {
  return call<void>("delete_credential", { provider, slot: slot ?? null });
}

export function getCredentialStatus(
  provider: string,
  slot?: string,
): Promise<CredentialStatus> {
  return call<CredentialStatus>("get_credential_status", { provider, slot: slot ?? null });
}

/**
 * What a connectivity test concluded.
 *
 * Three values, not two. `rejected` is the only one that means the credential is
 * at fault: `inconclusive` covers a provider outage and a malformed request of
 * ours, and telling a user their key is broken in either case would send them to
 * re-enter a working credential.
 */
export type ProbeVerdict = "valid" | "rejected" | "inconclusive" | "no_probe" | "no_secret";

export type ProbeOutcome = {
  provider: string;
  verdict: ProbeVerdict;
  status?: number;
  latencyMs?: number;
  /** A short provider message, or why nothing could be concluded. Never a secret. */
  detail?: string;
};

export function testProviderCredential(provider: string): Promise<ProbeOutcome> {
  return call<ProbeOutcome>("test_provider_credential", { provider });
}

/**
 * The worker's status, as `get_agent_status` returns it.
 *
 * The type itself lives in `lib/agentRuntime.ts` rather than here, because the
 * `agent_*` events carry the identical object and a second declaration of one
 * Rust struct is how an event payload and a polled payload come to disagree
 * without anybody noticing. It is a type-only import, so it costs nothing at
 * runtime and creates no cycle with the hook that lives beside it.
 */
export function getAgentStatus(): Promise<AgentStatus> {
  return call<AgentStatus>("get_agent_status");
}
// ---------------------------------------------------------------------------
// Setup gate
// ---------------------------------------------------------------------------

/** Whether one variable of a multi-part credential has a value. */
export type CredentialSlotStatus = {
  /** The variable this value belongs in. Doubles as the keyring slot name. */
  env: string;
  label: string;
  kind: "secret" | "url" | "text";
  help: string;
  /** A value is held in the OS keyring for this variable specifically. */
  stored: boolean;
  /** At most the final four characters, so three similar keys can be told apart. */
  storedLast4: string | null;
  /** A value is set in the environment for this variable specifically. */
  inEnv: boolean;
};

/** One provider the active profile cannot run without. */
export type RequiredCredential = {
  id: string;
  label: string;
  /** Where to get a key. Opened by the onboarding screen's button. */
  setupUrl?: string;
  /**
   * Environment variable *names* the worker reads. Never a value -- these are
   * documentation, and they are the only thing a user can act on when
   * configuring through `agent/.env` instead of this wizard.
   */
  keyEnv: string[];
  /**
   * One entry per `keyEnv` variable, in the same order, so the wizard draws a
   * field for each. Falls back to a single field derived from `keyEnv` when the
   * desktop layer is older and does not send them.
   */
  keySlots: {
    /** The variable the value belongs in. Doubles as the keyring slot name. */
    env: string;
    label: string;
    kind: "secret" | "url" | "text";
    help: string;
  }[];
  /**
   * Per-variable state, in the same order as `keySlots`.
   *
   * Without this a provider holding two of three values is undrawable: the
   * wizard can only show a field, and an empty field next to a stored one is
   * indistinguishable from having stored nothing. That is the shape behind
   * "it saved all three, but the last two were empty" and "reopening it showed
   * three empty fields" -- saving one value closed the whole group and the
   * group gave no credit for it.
   *
   * Empty on an older desktop layer, which is why every consumer falls back to
   * deriving slots from `keySlots`.
   */
  slots: CredentialSlotStatus[];
  /** What this provider is doing in the profile, for a subtitle. */
  capabilities: string[];
  /**
   * **Any** of this provider's variables is held in the OS keyring.
   *
   * A badge signal, and deliberately weaker than `missing.length === 0`. It is
   * true the moment one of LiveKit's three values lands, so nothing that decides
   * whether a call can be attempted may read it.
   */
  stored: boolean;
  storedLast4: string | null;
  inEnv: boolean;
  /** A local provider needs no credential at all, like Silero. */
  local: boolean;
  /**
   * Which of this provider's variables still have no value anywhere.
   *
   * A provider with one key is satisfied when this is empty or holds that one
   * name. A provider with several -- LiveKit needs a server address, an API key
   * and an API secret -- is only satisfied when it is empty, because two of
   * three is a credential that cannot connect.
   *
   * The gate used to ask only whether *any* value existed for the provider, which
   * is why it reported a LiveKit install with nothing usable as ready.
   */
  missing: string[];
};

export type SetupStatus = {
  required: RequiredCredential[];
  /** The single boolean the voice path gates on. */
  ready: boolean;
  activeProfile: string | null;
  /** True when a saved document governs rather than `agent/.env`. */
  configuredInApp: boolean;
  /** Why the configuration itself is not usable, in the worker's own words. */
  blocking: string[];
};

/**
 * Whether this install can hold a conversation yet.
 *
 * One call, because the answer needs the provider catalog, the keyring and the
 * worker's own validation, and assembling it in the webview would mean
 * reimplementing the reduction in TypeScript where it could disagree with the
 * worker. It reports *presence*, not validity: proving a key works costs a
 * billable request to a third party, and the Providers page has an explicit
 * "Test" for that.
 */
export function getSetupStatus(): Promise<SetupStatus> {
  return call<SetupStatus>("get_setup_status");
}

// ---------------------------------------------------------------------------
// Voice preview
// ---------------------------------------------------------------------------

/** The stage a preview renders, which is not necessarily the saved one. */
export type VoicePreviewRequest = {
  provider: string;
  model: string;
  voice?: string;
  options?: Record<string, string>;
};

export type VoicePreview = {
  /** A `data:` URI, ready for `HTMLAudioElement.src`. */
  dataUri: string;
  mimeType: string;
  sampleRate: number;
  channels: number;
  durationSeconds: number;
};

/**
 * Speak a short phrase with these exact settings, without saving them.
 *
 * A talking-speed slider is only usable if you can hear what it does. This takes
 * the *draft* stage, so a preview reflects an unsaved change — which is the whole
 * reason to have one. The synthesis goes through the worker's own stage builder, so
 * what you hear is the voice the session will use rather than an approximation of
 * it, and no room, agent, or session is involved.
 *
 * The credential never reaches here: it is read from the keyring on the Rust side
 * and put in the child process's environment. This request carries ids, numbers
 * and enum names only.
 */
export function previewVoice(request: VoicePreviewRequest, text?: string): Promise<VoicePreview> {
  return call<VoicePreview>("preview_voice", {
    fragment: { ...request, options: request.options ?? {} },
    text: text ?? null,
  });
}
